name: Cache Unity Library Folder
description: Caches the Unity Library folder
inputs:
  project-path:
    required: true
    description: Path that points to the Unity project folder
  target-platform: 
    required: true
    description: Valid Unity target platform identifier
  unity-version:
    required: true
    description: Valid Game CI Unity version identifier

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      with:
        path: ${{ inputs.project-path }}/Library
        key:
          Library-${{ inputs.unity-version }}-${{ inputs.project-path }}-${{ inputs.target-platform }}-${{ hashFiles(format('{0}/Assets/**', inputs.project-path), format('{0}/Packages/**', inputs.project-path), format('{0}/ProjectSettings/**', inputs.project-path)) }}
        restore-keys: |
          Library-${{ inputs.unity-version }}-${{ inputs.project-path }}-${{ inputs.target-platform }}-
          Library-${{ inputs.unity-version }}-${{ inputs.project-path }}-
          Library-${{ inputs.unity-version }}-
          Library-