name: Contributors List
description: | 
  Writes the contributors.json file to be read by the Unity project.
  Please note the API shortcomings: https://docs.github.com/en/rest/repos/repos#list-repository-contributors
  If we have more than 100 contributors, we need to page the result.
  If we have more than 500 contributors, not all will be shown anymore.
inputs:
  github-token:
    required: true
    description: GitHub Token
  ref:
    required: true
    description: The branch name to fetch
    default: develop
outputs:
  content:
    description: The JSON string containing build information.
    value: ${{ steps.content.outputs.value }}
  
runs:
  using: 'composite'
  steps:
    - name: Get Contributors from API
      id: variables
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "contributors=$(gh api -H 'Accept: application/vnd.github.VERSION.raw' '/repos/BoundfoxStudios/community-project/contents/.all-contributorsrc?ref=${{ inputs.ref }}' | jq --compact-output '[.contributors[] | { user: .name, githubAccount: .login, contributions: .contributions }]' )" >> $GITHUB_OUTPUT
      shell: sh
    - name: Write Build Manifest to JSON file
      id: content
      uses: BoundfoxStudios/action-set-text-output@v1
      with:
        text: ${{ steps.variables.outputs.contributors }}
