name: Development

on: 
  push:
    branches:
      - develop
      - 'feature/**'
    paths:
      - 'CommunityProject/Assets/**'
      - 'CommunityProject/Packages/**'
      - 'CommunityProject/ProjectSettings/**'
  pull_request:
    paths:
      - 'CommunityProject/Assets/**'
      - 'CommunityProject/Packages/**'
      - 'CommunityProject/ProjectSettings/**'

jobs: 
  build:
    name: Development
    uses: ./.github/workflows/build.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_PERSONAL_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_PERSONAL_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PERSONAL_PASSWORD }}
    with:
      target-platform: ${{ matrix.target-platform }}
      os: ${{ matrix.os }}
      custom-parameters: '-Development -AllowDebugging'
      do-test: true
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - macos-latest
        include:
          - os: windows-2019
            target-platform: StandaloneWindows64
          - os: macos-latest
            target-platform: StandaloneOSX