name: Documentation Website

on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: docs
      - run: npm run public
        working-directory: docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          user_name: "Boundfox Studios Publish Bot"
          user_email: "info@boundfoxstudios.com"
          commit_message: ":rocket: Deploy Docs (${{ github.event.head_commit.message }})"
