name: Build
concurrency: no-concurrency-due-to-license-activation

on: 
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request: 

jobs: 
  build:
    name: Build for ${{ matrix.targetPlatform }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        projectPath:
          - CommunityProject
        unityVersion:
          - 2021.3.9f1
        os: 
          - windows-2019
          - macos-latest
        include:
          - os: windows-2019
            targetPlatform: StandaloneWindows64
          - os: macos-latest
            targetPlatform: StandaloneOSX
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          buildName: CommunityProject
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          if-no-files-found: error
      - name: Return license after workflow cancellation
        uses: game-ci/unity-return-license@v2
        if: ${{ cancelled() }}
    