name: Project Management

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  assignIssueToCommenter:
    name: Assign Issue to Contributor
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue
        uses: bdougie/take-action@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          message: Danke, dass Du diese Aufgabe übernimmst! Falls Du Fragen hast, schreib sie einfach ins Issue!
          trigger: .meine-aufgabe
