name: Docs PRs

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on: 
  pull_request:
    types:
      - synchronize
      - opened
    branches-ignore:
      - main
    paths-ignore:
       - 'CommunityProject/Assets/**'
       - 'CommunityProject/Packages/**'
       - 'CommunityProject/ProjectSettings/**'

jobs: 
  lint: # Just for skipping required status checks
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  build: # Just for skipping required status checks
    name: Development Builds
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  
  label-successful-build: # Just for skipping required status checks
    name: Label succesful build
    runs-on: ubuntu-latest
    steps:
      - run: exit -