name: Unity PRs

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on: 
  pull_request:
    types:
      - synchronize
      - opened
    branches-ignore:
      - main
    paths:
       - 'CommunityProject/Assets/**'
       - 'CommunityProject/Packages/**'
       - 'CommunityProject/ProjectSettings/**'  
  
  pull_request_target:
    types:
      - labeled
    branches-ignore:
      - main
    paths:
       - 'CommunityProject/Assets/**'
       - 'CommunityProject/Packages/**'
       - 'CommunityProject/ProjectSettings/**'

jobs: 
  unlabel-ready-to-merge:
    name: Removes "ci-ready-to-merge" label on synchronize
    if: github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ci-ready-to-merge

  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request_target'
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - uses: ./.github/actions/linter

  build:
    needs: lint
    if: |
      github.event.action == 'labeled' 
      && contains(github.event.pull_request.labels.*.name, 'ci-reviewed')
    name: Development Builds
    uses: ./.github/workflows/build.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_PERSONAL_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_PERSONAL_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PERSONAL_PASSWORD }}
    with:
      do-test: true
      ref: "refs/pull/${{ github.event.number }}/merge"

  label-successful-build:
    needs: build
    if: success()
    name: Label succesful build
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ci-ready-to-merge

  unlabel-pr:
    needs: build
    name: Unlabel "ci-reviewed" PR
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ci-reviewed