name: Release
concurrency: no-concurrency-due-to-license-activation

on: 
  push:
    branches:
      - main

jobs: 
  build:
    name: Release
    uses: ./.github/workflows/build.yml
    secrets:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    with:
      target-platform: ${{ matrix.target-platform }}
      os: ${{ matrix.os }}
      do-test: true
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os:
          - windows-2019
          - macos-latest
        include:
          - os: windows-2019
            target-platform: StandaloneWindows64
          - os: macos-latest
            target-platform: StandaloneOSX