name: Release
concurrency: no-concurrency-due-to-license-activation

on: 
  push:
    branches:
      - main

jobs: 
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linter

  build:
    needs: lint
    name: Release
    uses: ./.github/workflows/build.yml
    secrets:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    with:
      do-test: true
      fail-fast: true
      max-parallel: 1
      ref: ${{ github.ref }}
  
  notarize:
    needs: build
    name: Notarize the macOS build
    uses: ./.github/workflows/notarization.yml
    secrets:
      APPLE_CERTIFICATE_DATA: ${{ secrets.APPLE_CERTIFICATE_DATA }}
      APPLE_CERTIFICATE_PASSPHRASE: ${{ secrets.APPLE_CERTIFICATE_PASSPHRASE }}
      APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
      APPLE_NOTARIZATION_USERNAME: ${{ secrets.APPLE_NOTARIZATION_USERNAME }}
      APPLE_NOTARIZATION_PASSWORD: ${{ secrets.APPLE_NOTARIZATION_PASSWORD }}
