# This workflow will automatically "skip" required checks if they will not run.
# The repository requires the game being build upon code changes.
# But it will skip those build, if only docs are changes.
# However this will block the PR from being merged.
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
# The link above describes the technique used here.

name: Development
on:
  pull_request:
    paths-ignore:
      - 'CommunityProject/Assets/**'
      - 'CommunityProject/Packages/**'
      - 'CommunityProject/ProjectSettings/**'
    branches-ignore:
      - main

jobs:
  lint: # Same job name required as in development.yml
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'

  build: # Same job name required as in development.yml
    name: Development Builds
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'